steps:
- name: gcr.io/cloud-builders/docker
  args: [build, '--build-arg', 'JAX_PACKAGE=jax[tpu]==0.6.2', '--build-arg', 'JAX_FIND_LINKS=https://storage.googleapis.com/jax-releases/libtpu_releases.html', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
